//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.0
//     from Assets/Imagenes/Controles.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Imagenes/Controles.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @Controles: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @Controles()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controles"",
    ""maps"": [
        {
            ""name"": ""PajarosVSCerdos"",
            ""id"": ""06a86d00-9616-4bfd-974c-15a7651c8146"",
            ""actions"": [
                {
                    ""name"": ""Presionado"",
                    ""type"": ""Button"",
                    ""id"": ""fbbbe6c8-16d6-4510-bb16-fa637726e069"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CanonArriba"",
                    ""type"": ""Value"",
                    ""id"": ""126a2aa9-619c-496d-8055-96c5eaa46204"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CanonAbajo"",
                    ""type"": ""Value"",
                    ""id"": ""c29e30bb-9ba4-471a-a150-e53ef5e8522d"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MasFuerza"",
                    ""type"": ""Value"",
                    ""id"": ""4673128c-33ca-4785-95e2-64ddcedf8acb"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MenosFuerza"",
                    ""type"": ""Value"",
                    ""id"": ""bbd7c643-053e-4f9c-af93-a2ae46f7478c"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c570123d-edc4-43ad-ada8-cd64ca531876"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Presionado"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""380c684f-347c-4fea-9485-fcacf1de5922"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CanonArriba"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e3fe4e17-9158-4f32-a237-0d46a04bd00a"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CanonAbajo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a94c0e4a-39f2-4af6-995a-1ce8d671d619"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MasFuerza"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7238be67-ce30-4d9f-8d68-71c0f505fb3f"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenosFuerza"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PajarosVSCerdos
        m_PajarosVSCerdos = asset.FindActionMap("PajarosVSCerdos", throwIfNotFound: true);
        m_PajarosVSCerdos_Presionado = m_PajarosVSCerdos.FindAction("Presionado", throwIfNotFound: true);
        m_PajarosVSCerdos_CanonArriba = m_PajarosVSCerdos.FindAction("CanonArriba", throwIfNotFound: true);
        m_PajarosVSCerdos_CanonAbajo = m_PajarosVSCerdos.FindAction("CanonAbajo", throwIfNotFound: true);
        m_PajarosVSCerdos_MasFuerza = m_PajarosVSCerdos.FindAction("MasFuerza", throwIfNotFound: true);
        m_PajarosVSCerdos_MenosFuerza = m_PajarosVSCerdos.FindAction("MenosFuerza", throwIfNotFound: true);
    }

    ~@Controles()
    {
        UnityEngine.Debug.Assert(!m_PajarosVSCerdos.enabled, "This will cause a leak and performance issues, Controles.PajarosVSCerdos.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PajarosVSCerdos
    private readonly InputActionMap m_PajarosVSCerdos;
    private List<IPajarosVSCerdosActions> m_PajarosVSCerdosActionsCallbackInterfaces = new List<IPajarosVSCerdosActions>();
    private readonly InputAction m_PajarosVSCerdos_Presionado;
    private readonly InputAction m_PajarosVSCerdos_CanonArriba;
    private readonly InputAction m_PajarosVSCerdos_CanonAbajo;
    private readonly InputAction m_PajarosVSCerdos_MasFuerza;
    private readonly InputAction m_PajarosVSCerdos_MenosFuerza;
    /// <summary>
    /// Provides access to input actions defined in input action map "PajarosVSCerdos".
    /// </summary>
    public struct PajarosVSCerdosActions
    {
        private @Controles m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public PajarosVSCerdosActions(@Controles wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "PajarosVSCerdos/Presionado".
        /// </summary>
        public InputAction @Presionado => m_Wrapper.m_PajarosVSCerdos_Presionado;
        /// <summary>
        /// Provides access to the underlying input action "PajarosVSCerdos/CanonArriba".
        /// </summary>
        public InputAction @CanonArriba => m_Wrapper.m_PajarosVSCerdos_CanonArriba;
        /// <summary>
        /// Provides access to the underlying input action "PajarosVSCerdos/CanonAbajo".
        /// </summary>
        public InputAction @CanonAbajo => m_Wrapper.m_PajarosVSCerdos_CanonAbajo;
        /// <summary>
        /// Provides access to the underlying input action "PajarosVSCerdos/MasFuerza".
        /// </summary>
        public InputAction @MasFuerza => m_Wrapper.m_PajarosVSCerdos_MasFuerza;
        /// <summary>
        /// Provides access to the underlying input action "PajarosVSCerdos/MenosFuerza".
        /// </summary>
        public InputAction @MenosFuerza => m_Wrapper.m_PajarosVSCerdos_MenosFuerza;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_PajarosVSCerdos; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="PajarosVSCerdosActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(PajarosVSCerdosActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="PajarosVSCerdosActions" />
        public void AddCallbacks(IPajarosVSCerdosActions instance)
        {
            if (instance == null || m_Wrapper.m_PajarosVSCerdosActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PajarosVSCerdosActionsCallbackInterfaces.Add(instance);
            @Presionado.started += instance.OnPresionado;
            @Presionado.performed += instance.OnPresionado;
            @Presionado.canceled += instance.OnPresionado;
            @CanonArriba.started += instance.OnCanonArriba;
            @CanonArriba.performed += instance.OnCanonArriba;
            @CanonArriba.canceled += instance.OnCanonArriba;
            @CanonAbajo.started += instance.OnCanonAbajo;
            @CanonAbajo.performed += instance.OnCanonAbajo;
            @CanonAbajo.canceled += instance.OnCanonAbajo;
            @MasFuerza.started += instance.OnMasFuerza;
            @MasFuerza.performed += instance.OnMasFuerza;
            @MasFuerza.canceled += instance.OnMasFuerza;
            @MenosFuerza.started += instance.OnMenosFuerza;
            @MenosFuerza.performed += instance.OnMenosFuerza;
            @MenosFuerza.canceled += instance.OnMenosFuerza;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="PajarosVSCerdosActions" />
        private void UnregisterCallbacks(IPajarosVSCerdosActions instance)
        {
            @Presionado.started -= instance.OnPresionado;
            @Presionado.performed -= instance.OnPresionado;
            @Presionado.canceled -= instance.OnPresionado;
            @CanonArriba.started -= instance.OnCanonArriba;
            @CanonArriba.performed -= instance.OnCanonArriba;
            @CanonArriba.canceled -= instance.OnCanonArriba;
            @CanonAbajo.started -= instance.OnCanonAbajo;
            @CanonAbajo.performed -= instance.OnCanonAbajo;
            @CanonAbajo.canceled -= instance.OnCanonAbajo;
            @MasFuerza.started -= instance.OnMasFuerza;
            @MasFuerza.performed -= instance.OnMasFuerza;
            @MasFuerza.canceled -= instance.OnMasFuerza;
            @MenosFuerza.started -= instance.OnMenosFuerza;
            @MenosFuerza.performed -= instance.OnMenosFuerza;
            @MenosFuerza.canceled -= instance.OnMenosFuerza;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PajarosVSCerdosActions.UnregisterCallbacks(IPajarosVSCerdosActions)" />.
        /// </summary>
        /// <seealso cref="PajarosVSCerdosActions.UnregisterCallbacks(IPajarosVSCerdosActions)" />
        public void RemoveCallbacks(IPajarosVSCerdosActions instance)
        {
            if (m_Wrapper.m_PajarosVSCerdosActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="PajarosVSCerdosActions.AddCallbacks(IPajarosVSCerdosActions)" />
        /// <seealso cref="PajarosVSCerdosActions.RemoveCallbacks(IPajarosVSCerdosActions)" />
        /// <seealso cref="PajarosVSCerdosActions.UnregisterCallbacks(IPajarosVSCerdosActions)" />
        public void SetCallbacks(IPajarosVSCerdosActions instance)
        {
            foreach (var item in m_Wrapper.m_PajarosVSCerdosActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PajarosVSCerdosActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="PajarosVSCerdosActions" /> instance referencing this action map.
    /// </summary>
    public PajarosVSCerdosActions @PajarosVSCerdos => new PajarosVSCerdosActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "PajarosVSCerdos" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="PajarosVSCerdosActions.AddCallbacks(IPajarosVSCerdosActions)" />
    /// <seealso cref="PajarosVSCerdosActions.RemoveCallbacks(IPajarosVSCerdosActions)" />
    public interface IPajarosVSCerdosActions
    {
        /// <summary>
        /// Method invoked when associated input action "Presionado" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPresionado(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "CanonArriba" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCanonArriba(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "CanonAbajo" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCanonAbajo(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "MasFuerza" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMasFuerza(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "MenosFuerza" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMenosFuerza(InputAction.CallbackContext context);
    }
}
